# Numpy

In [1]:
'''
Numpy is known as numeric python 
which is design for special functionality of multidimension array 
as we know python provides list,tuple,dictionary,set python's collection
framework
list is dynamic in data type and storage 
dictionary dynamic in data type and storage 
list works on based of linked list that means data stored in memory in 
linked list structure not continueous 

Array is collection of hemogenous data type values 
which is fixed in a size it was introduce by c langugae 

it is capable to store huge amount of single dimension as well as multi dimension values 
array is not dynamic in data type and storage and becasue of this thing it is faster data sctructure as compared 
to other data structure like list,tuple,dictionary etc.....

numpy developed in year 2005 using cpython interpreter and it is used to perform scientific operations on data 
wide used by data analist and data scientist 

when we work with anaconda numpy is already avaialble into anaconda package system 
but if i use basic python then core python not provide numpy we have to download and install it using pip command 
like 
pip install numpy (this will start installing numpy into your core python module directory) for this 
we required internet connection 
'''

"\nNumpy is known as numeric python \nwhich is design for special functionality of multidimension array \nas we know python provides list,tuple,dictionary,set python's collection\nframework\nlist is dynamic in data type and storage \ndictionary dynamic in data type and storage \nlist works on based of linked list that means data stored in memory in \nlinked list structure not continueous \n\nArray is collection of hemogenous data type values \nwhich is fixed in a size it was introduce by c langugae \n\nit is capable to store huge amount of single dimension as well as multi dimension values \narray is not dynamic in data type and storage and becasue of this thing it is faster data sctructure as compared \nto other data structure like list,tuple,dictionary etc.....\n\nnumpy developed in year 2005 using cpython interpreter and it is used to perform scientific operations on data \nwide used by data analist and data scientist \n\nwhen we work with anaconda numpy is already avaialble into an

In [2]:
import numpy as np
#! pip install numpy

# creating array

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype

dtype('int32')

In [6]:
l=[1,2.3,"abc",True]
print("list is hetrogeneous",type(l),l)
b=np.array(l)
print("Array is homogeneous",b)
print(b.dtype)

list is hetrogeneous <class 'list'> [1, 2.3, 'abc', True]
Array is homogeneous ['1' '2.3' 'abc' 'True']
<U32


In [7]:
b

array(['1', '2.3', 'abc', 'True'], dtype='<U32')

# Property of Numpy

In [8]:
a1=np.array([10,20,30,40,50])

In [9]:
a1 #print an array

array([10, 20, 30, 40, 50])

In [10]:
a1.ndim #dimension of an array

1

In [11]:
a1.shape #number of elements in array

(5,)

In [12]:
a1.size 

5

In [13]:
a1.itemsize # give how many byte occupied by data while processing array

4

# diff way of creating an array

In [14]:
# arange(start,stop,step)
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [15]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
x=np.linspace(1,2,5)

In [17]:
x

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
x.dtype

dtype('float64')

In [19]:
a=np.zeros(3)

In [20]:
a

array([0., 0., 0.])

In [21]:
v=np.ones(3)

In [22]:
v

array([1., 1., 1.])

In [23]:
np.eye(3) #create 2 dimension array 3x3 size with identity matrics

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
k=np.array([1,2,3],dtype='float')

In [25]:
k

array([1., 2., 3.])

# MultiDimension Array

In [26]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [27]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
np.array([[2,3,4],[5,6,7]]).reshape(6,)

array([2, 3, 4, 5, 6, 7])

In [29]:
a=np.random.randn(24).reshape(4,2,3)

In [30]:
a

array([[[ 0.89189384, -0.40425203, -0.19066131],
        [-0.66060621, -0.96626477,  0.49784381]],

       [[-1.52920402, -0.44366245,  1.20974106],
        [-0.87137545,  0.98936858,  1.08627434]],

       [[ 0.46822502, -0.19307852,  0.05336868],
        [ 1.06377254,  0.82050736, -0.61626884]],

       [[-0.19121506,  1.72139941, -0.44214329],
        [-0.36543845,  0.09638496,  0.25653993]]])

In [31]:
a.dtype

dtype('float64')

In [32]:
a.itemsize

8

In [33]:
a.size

24

In [34]:
a.shape

(4, 2, 3)

In [35]:
a.ndim

3

# Array Functions

In [36]:
a

array([[[ 0.89189384, -0.40425203, -0.19066131],
        [-0.66060621, -0.96626477,  0.49784381]],

       [[-1.52920402, -0.44366245,  1.20974106],
        [-0.87137545,  0.98936858,  1.08627434]],

       [[ 0.46822502, -0.19307852,  0.05336868],
        [ 1.06377254,  0.82050736, -0.61626884]],

       [[-0.19121506,  1.72139941, -0.44214329],
        [-0.36543845,  0.09638496,  0.25653993]]])

In [37]:
x

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [38]:
a.sum()

2.281149111051784

In [39]:
x.sum()

7.5

In [40]:
k=np.arange(10,20).reshape(2,5)

In [41]:
k

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
k.sum()

145

In [43]:
# axis 0 means columns
# axis 1 means rows 
k.sum(axis=0) #column wise sum

array([25, 27, 29, 31, 33])

In [44]:
k.sum(axis=1) #row wise sum

array([60, 85])

In [45]:
k.min()

10

In [46]:
k.max()

19

In [47]:
k.min(axis=0)

array([10, 11, 12, 13, 14])

In [48]:
k.min(axis=1)

array([10, 15])

In [49]:
k.mean() #calculating average

14.5

In [50]:
k.var() #used calculate variance

8.25

In [51]:
k.std() #used to calculate deviation of our data 

2.8722813232690143

# Numpy Functions

In [52]:
a=np.array([1,1,2,2,2,2,2,3,3,3,4,4,5,6,7,8,9])

In [53]:
a

array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9])

In [54]:
np.mean(a) # average 

3.764705882352941

In [55]:
np.median(a) # after sorting all observation middle number is median

3.0

In [56]:
np.bincount(a).argmax() # highst frequncy number mode 

2

In [57]:
a=np.array([-15,1,1,2,2,2,2,2,3,3,3,4,4,5,6,7,8,9,100])

In [58]:
a

array([-15,   1,   1,   2,   2,   2,   2,   2,   3,   3,   3,   4,   4,
         5,   6,   7,   8,   9, 100])

In [59]:
#-15 is extream value lowest 
#100 is highest extream values
a

array([-15,   1,   1,   2,   2,   2,   2,   2,   3,   3,   3,   4,   4,
         5,   6,   7,   8,   9, 100])

In [60]:
q1=np.quantile(a,0.25)

In [61]:
q1

2.0

In [62]:
q3=np.quantile(a,0.75)

In [63]:
q3

5.5

In [64]:
IQR=q3-q1

In [65]:
IQR

3.5

In [66]:
#uppler IQR upper whiskers 
upper_range=q3+1.5*IQR

In [67]:
upper_range

10.75

In [68]:
lower_range=q1-1.5*IQR

In [69]:
lower_range

-3.25

# Maths functions

In [70]:
np.sin(90)

0.8939966636005579

In [71]:
np.cos(90)

-0.4480736161291701

In [72]:
np.log(10)

2.302585092994046

In [73]:
np.log(1)

0.0

In [74]:
np.log10(10)

1.0

In [75]:
np.log(np.log10(5))

-0.35814744992084513

In [76]:
np.sqrt(144)

12.0

In [88]:
a=np.array([1,2,2,3,3,3,4,4,16,20,25])

In [89]:
a

array([ 1,  2,  2,  3,  3,  3,  4,  4, 16, 20, 25])

In [90]:
np.mean(a)

7.545454545454546

In [91]:
np.median(a)

3.0

In [92]:
'''
skew is part of measure of dispertion indicates your observation skewd in which direction if observation skewd right side that means 
it is positively skewd and it is not normally distributed and i can say positive outliers presnt in data which may 
lead us to bias output of our ml model 
same thing happen when your data is skewd to left hand side that means data is negatively skewd which may lead us to bias output of 
our ml model 
to train our model on based data we need optimal and maximum normally distributed bu if my real time data is 
not normally distributed i have to transform those data by applying some maths on it into near to normally distrubted 

in word 80% is near to normally distributed as a ml developer we have check domain and according we have to work 

'''
from scipy.stats import skew

In [84]:
skew(a)

1.1712731595847037

In [97]:
a=np.array([1,2,2,3,3,3,4,4,16,20,25])

In [94]:
a=np.sqrt(a)

In [95]:
a

array([1.        , 1.41421356, 1.41421356, 1.73205081, 1.73205081,
       1.73205081, 2.        , 2.        , 4.        , 4.47213595,
       5.        ])

In [96]:
skew(a)

0.9630668329521322

In [98]:
a1=np.arange(10,16).reshape(3,2)

In [99]:
a1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [100]:
a2=np.arange(16,22).reshape(3,2)

In [101]:
a2

array([[16, 17],
       [18, 19],
       [20, 21]])

In [102]:
x1=np.concatenate([a1,a2])

In [103]:
x1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [104]:
#axis 0 means column 
#axis 1 means rows 
# by default concatenate function of numpy will perform axis 0 base concate
x2=np.concatenate([a1,a2],axis=1)

In [105]:
x2

array([[10, 11, 16, 17],
       [12, 13, 18, 19],
       [14, 15, 20, 21]])

In [106]:
x1=np.concatenate([a1,a2],axis=0)

In [107]:
x1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [109]:
#find unique values from array 
np.unique([1,1,2,3])

array([1, 2, 3])

In [110]:
np.unique([1,1,2,3],return_counts=True)

(array([1, 2, 3]), array([2, 1, 1], dtype=int64))

In [ ]:
'''
what is measure of dispertion or deviation ?
daviation means how far your data from mean value
it consider each and every observation to find avg deviation of our data 
to do so we need 
1)find mean of our data
2)subtract observtion from mean using absolute 
3)now summetion of all summetion|x-M|/number of observation 
above will help us to get mean absolute daviation (MAD)

standard deviation is used squre instead of absolute values and then it calculate squreroot of av of daviated values

MAD (both are used for measure of dispertion) absolute
SD (square and then calculate square root)

find differance between this and find why this 2 methods exist 
'''

# Indexing and slicing

In [111]:
a=np.arange(10,20).reshape(5,2)

In [112]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [113]:
#a[row][column]
a[1] #row index 1 values

array([12, 13])

In [114]:
a[1][1] #row index 1 and column index 1 value

13

In [115]:
#as per slicing [start:stop:step] , indicates rest of other values
a[2:4,] #row index 2 to 4 all values

array([[14, 15],
       [16, 17]])

In [116]:
a[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [118]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [119]:
a[2:4,1] #2 to 4 rows we want 1 index values

array([15, 17])

In [120]:
a[2,0]

14

In [121]:
a[2][0]

14

In [122]:
a[3,1]

17

In [123]:
a[[0,2]]

array([[10, 11],
       [14, 15]])

In [124]:
a[[0,2],1]

array([11, 15])

# Boolean Indexing

In [125]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [126]:
a>15

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [127]:
a[a>15]

array([16, 17, 18, 19])

In [128]:
a[a%2==0]

array([10, 12, 14, 16, 18])

# vectorization

In [129]:
a=np.array([1,2,3])

In [130]:
s=10

In [131]:
a+s

array([11, 12, 13])

In [132]:
np.array([1,2,3])*10

array([10, 20, 30])

# Broadcasting

In [133]:
a1=np.array([[1,2],[3,4]])

In [134]:
a2=np.array([2,3])

In [135]:
a1

array([[1, 2],
       [3, 4]])

In [136]:
a2

array([2, 3])

In [138]:
a3=a1+a2

In [139]:
a3

array([[3, 5],
       [5, 7]])

# cross vs dot product

In [140]:
#matrics operation is cross product and . product 
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])

In [141]:
a1

array([[1, 2],
       [3, 4]])

In [142]:
a2

array([[5, 6],
       [7, 8]])

In [143]:
#cross product
a1*a2

array([[ 5, 12],
       [21, 32]])

In [144]:
# dot product give matrix multiplication 
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [145]:
a1

array([[1, 2],
       [3, 4]])

In [146]:
a2

array([[5, 6],
       [7, 8]])