# Support Vector Machine

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv("data/mobile.csv")

In [3]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            0  
1        1             1     0            1  
2        1             1     0            1  
3        1             0     0            1  
4        1             1     0            0  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
battery_power    2000 non-null int64
blue             2000 non-null int64
clock_speed      2000 non-null float64
dual_sim         2000 non-null int64
fc               2000 non-null int64
four_g           2000 non-null int64
int_memory       2000 non-null int64
m_dep            2000 non-null float64
mobile_wt        2000 non-null int64
n_cores          2000 non-null int64
pc               2000 non-null int64
px_height        2000 non-null int64
px_width         2000 non-null int64
ram              2000 non-null int64
sc_h             2000 non-null int64
sc_w             2000 non-null int64
talk_time        2000 non-null int64
three_g          2000 non-null int64
touch_screen     2000 non-null int64
wifi             2000 non-null int64
price_range      2000 non-null int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB


In [5]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.3)

# Simple linear SVM

In [7]:
from sklearn.svm import LinearSVC

In [8]:
lsv=LinearSVC(random_state=1)

In [9]:
lsv.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=1, tol=0.0001,
          verbose=0)

In [10]:
y_pred=lsv.predict(x_test)

In [11]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.54      1.00      0.70       284
           1       0.99      0.24      0.39       316

    accuracy                           0.60       600
   macro avg       0.76      0.62      0.54       600
weighted avg       0.78      0.60      0.54       600



# soft margin

In [13]:
lsv2=LinearSVC(C=0.2,random_state=1)

In [14]:
lsv2.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=0.2, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=1, tol=0.0001,
          verbose=0)

In [15]:
y_pred=lsv2.predict(x_test)

In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.54      1.00      0.70       284
           1       0.99      0.24      0.39       316

    accuracy                           0.60       600
   macro avg       0.76      0.62      0.54       600
weighted avg       0.78      0.60      0.54       600



In [17]:
lsv2.coef_

array([[ 4.89692003e-04, -5.19809040e-03, -1.01697995e-02,
        -6.05776999e-03,  4.10116815e-03, -3.93810609e-03,
        -8.26906459e-03, -3.98670779e-03, -8.98200742e-03,
        -2.25836998e-02, -1.73797644e-02,  9.25315772e-05,
        -1.46955473e-04,  6.26255238e-04, -4.39053149e-02,
        -6.28050326e-03, -3.14220124e-02, -4.69379287e-03,
        -5.46435639e-03, -4.28172557e-03]])

In [18]:
lsv2.intercept_

array([-0.00767285])

# Kernal Functions

In [19]:
from sklearn.svm import SVC

In [20]:
svc = SVC(random_state=1,kernel="poly") #polynomial 

In [21]:
svc.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [22]:
y_pred=svc.predict(x_test)

In [23]:
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       284
           1       0.98      0.98      0.98       316

    accuracy                           0.98       600
   macro avg       0.98      0.98      0.98       600
weighted avg       0.98      0.98      0.98       600



In [25]:
# the data was not linearly separable so when we use polynomial at that time 
#hyperplabe pattern was polynomial to separate our data


# Gridsearch SVM

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
C=[1.0,0.25,0.5,0.75]
kernel=["linear","rbf"]
gamma=["auto",0.01,0.001,0.0001,1]
decision_function_shape=["ovo","ovr"]
#ovr = one vs rest
#one vs one 

In [33]:
svmg=SVC(random_state=1)
grid_svm=GridSearchCV(estimator=svmg,cv=5,param_grid=dict(kernel=kernel,C=C, gamma=gamma, decision_function_shape=decision_function_shape),verbose = 5
                     )
grid_svm.fit(x_train,y_train)
print("best score: ", grid_svm.best_score_)
print("best param: ", grid_svm.best_params_)
#so it is also gives cross fold validation so my model will be trained with all possible 
#patterns 

Fitting 5 folds for each of 80 candidates, totalling 400 fits
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear ...


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.996, total=   7.1s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear ...


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.0s remaining:    0.0s


[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.989, total=   1.6s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear ...


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    8.5s remaining:    0.0s


[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.986, total=   3.8s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear ...


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   12.4s remaining:    0.0s


[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.989, total=   1.1s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear ...


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:   13.4s remaining:    0.0s


[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.986, total=   6.0s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.514, total=   0.3s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=1.0, decision_function_shape=ovo, gamma=0.01, kernel=linear ...
[CV]  C=1.0, 

[CV]  C=1.0, decision_function_shape=ovr, gamma=auto, kernel=linear, score=0.986, total=   6.6s
[CV] C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.514, total=   0.3s
[CV] C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=1.0, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=1.0, decision_function_shape=ovr, gamma=0.01, kernel=linear ...
[CV]  C=1.0, 

[CV]  C=0.25, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.986, total=   2.2s
[CV] C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.514, total=   0.2s
[CV] C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.25, decision_function_shape=ovo, gamma=0.01, kernel=linear ..
[CV]  C

[CV]  C=0.25, decision_function_shape=ovr, gamma=auto, kernel=linear, score=0.986, total=   2.5s
[CV] C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.514, total=   0.3s
[CV] C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.25, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.25, decision_function_shape=ovr, gamma=0.01, kernel=linear ..
[CV]  C

[CV]  C=0.5, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.986, total=   3.2s
[CV] C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.514, total=   0.2s
[CV] C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.5, decision_function_shape=ovo, gamma=0.01, kernel=linear ...
[CV]  C=0.5, 

[CV]  C=0.5, decision_function_shape=ovr, gamma=auto, kernel=linear, score=0.986, total=   3.6s
[CV] C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.514, total=   0.3s
[CV] C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf ......
[CV]  C=0.5, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.3s
[CV] C=0.5, decision_function_shape=ovr, gamma=0.01, kernel=linear ...
[CV]  C=0.5, 

[CV]  C=0.75, decision_function_shape=ovo, gamma=auto, kernel=linear, score=0.986, total=   4.2s
[CV] C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.514, total=   0.2s
[CV] C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovo, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovo, gamma=0.01, kernel=linear ..
[CV]  C

[CV]  C=0.75, decision_function_shape=ovr, gamma=auto, kernel=linear, score=0.986, total=   4.2s
[CV] C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.514, total=   0.2s
[CV] C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf .....
[CV]  C=0.75, decision_function_shape=ovr, gamma=auto, kernel=rbf, score=0.511, total=   0.2s
[CV] C=0.75, decision_function_shape=ovr, gamma=0.01, kernel=linear ..
[CV]  C

[Parallel(n_jobs=1)]: Done 400 out of 400 | elapsed: 10.7min finished


best score:  0.99
best param:  {'C': 0.25, 'decision_function_shape': 'ovo', 'gamma': 'auto', 'kernel': 'linear'}


In [29]:
#in general summery which parameters and kernal gives best result 
# as we know SVM is very tough to understand as well as to plot it 
# it also complicated while selecting kernal 
'''so gridsearch where we provide all possible parameters and kernal and it 
will give summary which parameters are giving better result so we can train model with
those parameters finally.'''

'so gridsearch where we provide all possible parameters and kernal and it \nwill give summary which parameters are giving better result so we can train model with\nthose parameters finally.'

In [40]:
# we can see all iteration it is showing to us.

In [41]:
'''
best score:  0.96375
best param:  {'C': 2, 'decision_function_shape': 'ovo', 'gamma': 'auto', 'kernel': 'linear'}
'''

"\nbest score:  0.96375\nbest param:  {'C': 2, 'decision_function_shape': 'ovo', 'gamma': 'auto', 'kernel': 'linear'}\n"

In [42]:
svm_model=SVC(C=2,decision_function_shape="ovo",gamma="auto",kernel="linear",random_state=1)
svm_model.fit(x_train,y_train)

SVC(C=2, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [43]:
y_pred=svm_model.predict(x_test)

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       284
           1       0.99      0.97      0.98       316

    accuracy                           0.98       600
   macro avg       0.98      0.98      0.98       600
weighted avg       0.98      0.98      0.98       600

